# docker compose -f docker-compose.debug.yml up --build

version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # панель управління

  gateway:
    build:
      context: .
      args:
        APP_NAME: gateway
        BUILD_MODE: debug
    ports:
      - "3000:3000"
      - "9230:9229"
    depends_on:
      - accounts
      - logger
      - rabbitmq
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgres://user:password@db:5432/bank_db
      - DB_HOST=db
      - ACCOUNTS_HOST=accounts
      - LOGGER_HOST=logger
      - BUILD_MODE=debug
      - APP_NAME=gateway
    command: []

  accounts:
    build:
      context: .
      args:
        APP_NAME: accounts
        BUILD_MODE: debug
    ports:
      - "3001:3001"
      - "9231:9229"
    depends_on:
      - db
      - rabbitmq
      - logger
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bank_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=db
      - LOGGER_HOST=logger
      - BUILD_MODE=debug
      - APP_NAME=accounts
    command: []

  logger:
    build:
      context: .
      args:
        APP_NAME: logger
        BUILD_MODE: debug
    ports:
      - "3002:3002"
      - "9232:9229"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bank_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - BUILD_MODE=debug
      - DB_HOST=db
      - APP_NAME=logger
    command: []

volumes:
  postgres_data: