# docker compose -f docker-compose.debug.yml up --build

version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      gateway:
        condition: service_healthy # 👈 Чекаємо, поки NestJS шлюз повністю прокинеться і пройде healthcheck
    environment:
      - PORT=3000
      - NODE_ENV=production
      # Ця лінка полетить у браузер клієнта:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:2999
      # Цю лінку ми використовуємо для Logout в шлюзі:
      - FRONTEND_URL=http://localhost:3000/
      # Якщо твій SSR робить серверні запити під час рендерингу (наприклад, fetch у page.tsx):
      # Переконайся, що функція getUserData() або аналогічні на серверній стороні Next.js
      # використовують саме цей хост, якщо працюють в Docker, або підміняють його.
      - INTERNAL_GATEWAY_URL=http://gateway:2999

  gateway:
    container_name: gateway
    stop_grace_period: 15s
    build:
      context: .
      args:
        APP_NAME: gateway
        BUILD_MODE: debug
    ports:
      - "2999:2999"
      - "9230:9229"
    depends_on:
      - accounts
      - auth
      - logger
      - rater
    environment:
      - PORT=2999
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - ACCOUNTS_HOST=accounts
      - AUTH_HOST=auth
      - LOGGER_HOST=logger
      - RATER_HOST=rater
      - APP_NAME=gateway
    healthcheck:
      # Перевіряємо, чи відкрився порт 2999 всередині контейнера за допомогою Node.js
      test: ["CMD-SHELL", "node -e \"const net = require('net'); const client = net.connect({port: 2999, host: 'localhost'}, () => { client.end(); process.exit(0); }); client.on('error', () => process.exit(1));\""]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  auth:
    container_name: auth
    stop_grace_period: 15s
    build:
      context: .
      args:
        APP_NAME: auth
        BUILD_MODE: debug
    ports:
      - "3003:3003"
      - "9233:9229"
    depends_on:
      - db
      - rabbitmq
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://user:password@db:5432/auth_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - APP_NAME=auth
    healthcheck:
      # test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      # test: ["CMD-SHELL", "grep -q \"1628 01\" /proc/net/tcp"]
      test: ["CMD-SHELL", "awk '$4 == \"01\" && $3 ~ /:1628$/ { found=1 } END { exit found ? 0 : 1 }' /proc/net/tcp /proc/net/tcp6"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  accounts:
    container_name: accounts
    stop_grace_period: 15s
    build:
      context: .
      args:
        APP_NAME: accounts
        BUILD_MODE: debug
    ports:
      - "3001:3001"
      - "9231:9229"
    depends_on:
      - db
      - rabbitmq
      - redis
      - rater
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bank_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - RATER_GRPC_URL=rater:3004
      - APP_NAME=accounts
    healthcheck:
      test: ["CMD-SHELL", "awk '$4 == \"01\" && $3 ~ /:1628$/ { found=1 } END { exit found ? 0 : 1 }' /proc/net/tcp /proc/net/tcp6"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  logger:
    container_name: logger
    stop_grace_period: 15s
    build:
      context: .
      args:
        APP_NAME: logger
        BUILD_MODE: debug
    ports:
      - "3002:3002"
      - "9232:9229"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/audit_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - APP_NAME=logger
    healthcheck:
      test: ["CMD-SHELL", "awk '$4 == \"01\" && $3 ~ /:1628$/ { found=1 } END { exit found ? 0 : 1 }' /proc/net/tcp /proc/net/tcp6"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  rater:
    container_name: rater
    stop_grace_period: 15s
    build:
      context: .
      args:
        APP_NAME: rater
        BUILD_MODE: debug
    ports:
      - "3004:3004"
      - "9234:9229"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
      - APP_NAME=rater
    healthcheck:
      # через утиліту grpc_health_probe:
      # test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:3004"]
      # Намагаємося відкрити "сирий" TCP сокет на порт 3004. Якщо порт слухає — сокет відкриється успішно.
      test: ["CMD-SHELL", "node -e \"const net = require('net'); const client = net.connect({port: 3004, host: 'localhost'}, () => { client.end(); process.exit(0); }); client.on('error', () => process.exit(1));\""]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
  redis_data:
